# your domain
domain: example.com
#domain: 127.0.0.1

# database dsn(postgresql)
# 暂不支持远程数据库，留空以启用本地数据库默认连接参数
database_url: ""

# cloudflare api
cf_email: ""
cf_key: ""

# source definition file
source-files:
  # use local file
  - ./config/source.yaml
  # use web file
  - https://hub.tgbot.co/proxy/webfuzz.yaml
  - https://hub.tgbot.co/proxy/tgchannel.yaml
  - https://hub.tgbot.co/proxy/subscribe.yaml
  - https://hub.tgbot.co/proxy/others.yaml
  - https://hub.tgbot.co/proxy/clash.yaml
